### PR TITLE
Suggestion for restructure.

### PR DESCRIPTION
**Pull request by m-ou-se**
Hey,

I was thinking: Maybe the code can be split, such that the part that does all the calculations is separate from the part that does the actual conversion to decimal/ascii. So, split it right between 'Step 4' and 'Step 5'.

I experimented a bit, and the result is a function that does step 1 till 4 and returns a small struct with the results, and a separate function which takes that struct to perform step 5. There could be multiple versions of this last function if you want to support different formats. It might also be useful for a user to only call the first function, if they have special requirements on the formatting.

Let me know if you'd like me to continue with this. (This pull-request is not ready to be merged yet.)

### CODE REVIEW

**Comment by ulfjack** [comment]
Cool! Did you see the discussion in #30? The proposal is to drop the sign bit from the return value so that the compiler can optimize it to return as two registers. (Maybe it can also do that if the sign bit is included? Might be worth checking godbolt.) I'm a bit concerned about performance - at the current level, I think we'll see the additional method call in the benchmark. We probably have to do it anyway.

**Comment by m-ou-se** [comment]
The struct with the sign bit still fits in two registers, as the exponent is only 16 bits. (And for 32-bit floats, even an 8-bit exponent would be enough.)

I did run the benchmarks before and after, and it seems a few percent slower.

**Comment by ulfjack** [comment]
I would prefer to go in smaller steps so that we can see - at each point - whether it affects performance or not.

I took a small part of your change and pushed it to https://github.com/ulfjack/ryu/tree/floating-decimal.
As far as I can tell, this does not regress performance (due to inlining, I think). If you don't mind, I'd like to merge that part and then continue from there.

I'm not sure if a struct with three fields will even be passed as two registers even if it's technically possible. However, we could reduce this to two fields by merging the sign into the digits field. What do you think?

**Comment by ulfjack** [comment]
I created a pull request from my branch.

**Comment by ulfjack** [comment]
I'm going to close this due to lack of progress. While I've made some progress at exposing a lower-level API, I haven't found a way that doesn't come with a performance cost. I'd be happy to get further input on the topic in any form (pull requests, bugs, emails). I have seen some forks due to incompatible formatting requirements, and a low-level API would significantly improve the outlook on that front.

**Pull request closed without merging**
