### PR TITLE
Add an intermediate rep between digit gen and string gen

### PR DESCRIPTION
**Pull request by ulfjack**
This is based on the change by @m-ou-se, #35, but only a small part of it. As far as I can tell, this does not regress performance.

I'm not sure if a struct with three fields will ever be passed as two registers even if it's technically possible. However, we could reduce this to two fields by merging the sign into the digits field. We might want to experiment with that.

Progress on #30.

### CODE REVIEW

**Comment by ulfjack** [comment]
I've added a patch to do just that.

**Comment by ulfjack** [comment]
Seems to be fine performance-wise.

**Comment by m-ou-se** [comment]
On x86-64, such a struct with three fields is also passed in registers, as long as `sizeof` is 16 or less.

**Comment by mitchblank** [comment]
@ulfjack / @m-ou-se -- I still don't think it's actually beneficial for the "low level" function to return information about the value's sign.  Let me explain my reasoning:
* What to do about the non-finite and zero cases is fundamentally a question of for the presentation layer.  Therefore, the most natural way to start is to have the "presentation layer" convert `double`->`uint64_t` conversion itself, handle those edge cases, and then just pass the `uint64_t` into the "low-level" function.  The low-level function would just map `uint64_t`->`floating_decimal_64`
* The low-level function then doesn't care about the sign bit at all.  So it it is going to include that information in *its* return value, it would only be for the convenience of its caller.
* However, in this design that information *would not* be useful to the caller.  Since the caller already has the `uint64_t` holding the IEEE754 bits, it can test the sign bit itself.  i.e. do something like...
```
if (d & SIGN_BIT)
  *p++ = '-';
```
Note that from the CPU's perspective this is actually perfect -- the optimizer will implement that `if` statement with a single `blt` instruction -- testing the high-bit of a register is something the CPU is very well set up to do!

So basically by doing something like returning a negative mantissa for negative input you're actually making the caller do slightly more work (un-negating the mantissa).  There just isn't any benefit.

So I would sketch an API like:
```
// Returns true if "d" represents a "special" ieee754 (Inifinite, NaN, zero) which to_floating_decimal_64() isn't prepared for
static inline bool ieee754_double_bits_are_special(uint64_t bits)
{
  static const uint64_t exponent_bits = ((uint64_t) 1023) << 52;
  if (bits & exponent_bits == exponent_bits)
    return true; // +/- Infinite or NaN
  static const uint64_t sign_bit = ((uint64_t) 1) << 63;
  if (bits & ~sign_bit == 0)
    return true;  // zero
  return false;
}

static inline bool ieee754_double_bits_are_negative(uint64_t bits)
{
  static const uint64_t sign_bit = ((uint64_t) 1) << 63;
  return (bits & sign_bit) != 0;
}

// Low level function that takes a finite, non-zero IEEE754 bit representation
// and finds the integer that represents the digits that appear in the shortest
// decimal representation, along with the decimal exponent.
extern struct floating_decimal_64 to_floating_decimal_64(uint64_t bits);
```

If you want to have `to_floating_decimal_64` return more information as part of `struct floating_decimal_64` I'd suggest maybe adding `olength` since that is something I think that the low-level code currently computes for its own needs that the presentation layer could make use of as well (even though it could be recomputed from the returned mantissa integer).

**Comment by ulfjack** [comment]
@mitchblank, I see your point. Please take a look at #39, which works similar to how you propose. I don't pass in the uint64_t since the presentation layer already has to decode it into mantissa and exponent, and by passing in mantissa and exponent explicitly, I avoid double-decoding the number (although it's probably not that costly). For some unknown reason, the code got a little faster in the process.

**Comment by mitchblank** [comment]
> since the presentation layer already has to decode it into mantissa and exponent

I don't think that's actually true -- for the simple needs of the presentation layer (i.e. classifying zero/infinite/NaN) it's simple enough to just do bit masking on the `uint64_t` directly, as per my `inline bool ieee754_double_bits_*()` helpers above.  (It's especially better for 32-bit CPUs since, unlike shift, and/or/xor/not can be done on a pair of 32-bit registers in-situ.  Shifting a uint64_t by is actually quite complicated, but I think we're probably lucky in that we're shifting by >= 32: https://godbolt.org/g/G2YJNy)

But anyway, I don't think it makes a big difference which side ends up splitting the mantissa/exponent, so whatever you're happy with.  If we passed it in to the lower layer as a `uint64_t` the first thing it would do is split it into two registers, so it doesn't make a difference if the calling convention has placed that information into two registers already.

**Comment by ulfjack** [comment]
But then we still need to shift in the conversion layer in the common case. I'm not sure it's noticeable, but we're already haggling over 0.5ns. :-)

**Pull request merged**
