### PR TITLE
Use log10 from Hacker's Delight

### PR DESCRIPTION
**Pull request by ulfjack**
This is slightly slower with my original benchmark, which is a bit
unrealistic since it converts the same number 1000 times, so it gets
perfect branch prediction.

As a demo, I changed the benchmark to pre-generate a list of 1000
random numbers and convert each of them for each of the outer loops.
In this scenario, the algorithm from Hacker's Delight is a tiny bit
faster. Note that the benchmark returns generally higher times,
probably due to the branch prediction misses). It is arguable whether
this benchmark is more or less representative of real programs.

### CODE REVIEW

**Comment by ulfjack** [comment]
This isn't going to pass on CI since it was written on Windows.

**Comment by StephanTLavavej** [comment]
With the recently updated benchmark, I observe a small but consistent performance regression from these changes, for both MSVC x64 and Clang 7 RC1 x64. For MSVC it's 0.7% slower and for Clang it's 1.2% slower.

**Comment by jorgbrown** [comment]
You can get even a little better than this, by using an additional table to get rid of the multiply.  See https://godbolt.org/g/vtBEXm for code.

**Comment by jorgbrown** [comment]
You can get even a little better than this, by using an additional table to get rid of the multiply. See https://gcc.godbolt.org/z/EUH6VQ for code.  (Previous comment used wrong URL)

( For test code, we can make a constexpr version: https://godbolt.org/g/a2iX25 )

**Comment by ulfjack** [comment]
I'm on vacation out of country for two weeks. I'll take a look when I'm back. I can approve pull requests, if someone else wants to take a look first - note that this needs to be ported to linux/macos before it can be merged (if it's a performance improvement).

**Comment by ulfjack** [comment]
Unfortunately, it looks like it's not an improvement, even with the updated benchmark. :-(

**Pull request closed without merging**
