### PR TITLE
Alternative float to bit conversion

### PR DESCRIPTION
**Pull request by marler8997**
Was porting this to another language and thought of another way to implement float/double to bits.

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
That approach (which would be a `reinterpret_cast` in C++) violates “strict aliasing” rules, which can lead optimizers to generate incorrect code. The `memcpy()` approach, while strange-looking, obeys strict aliasing and is guaranteed to be correct.

**Comment by marler8997** [comment]
@StephanTLavavej thanks for the explanation.  I wasn't aware of this problem.  I didn't know that compilers could assume that two pointers with the same address and different types could be pointing to distinct values, which is what I understand to be the problem after reading the article.

Anyway, this article (https://xania.org/200712/cpp-strict-aliasing) suggests using a union.  I've updated my PR to use that instead.  I could look at the assembly to see how it affects the code, but I assume that what will probably amount to a `MOV` instruction or similar would be preferable over a function call?

**Comment by marler8997** [comment]
P.S. @StephanTLavavej I thought I recognized you...watched your cppcon talks a while back :)

**Comment by StephanTLavavej** [comment]
Please see https://godbolt.org/z/jyDpST - Clang, GCC, and MSVC are all aware of this `memcpy()` idiom and optimize it away, without emitting CRT function calls.

**Comment by marler8997** [comment]
Impressive, though, it's disappointing to see that the the compiler has chosen to assume the implementation of certain functions.

In any case, both implementations seem to produce the same assembly  when optimizations are turned on.  However, without optimization, the implementations differ.  Not sure which one is better though.  I'm just trying to see if one implementation has any advantage over the other.

**Comment by marler8997** [comment]
Current implementation: `float_to_bits1`
Proposed implementation: `float_to_bits2`

MSVC:
```asm
bits$ = 32
f$ = 64
unsigned int float_to_bits1(float) PROC                            ; float_to_bits1
$LN3:
        movss   DWORD PTR [rsp+8], xmm0
        sub     rsp, 56                             ; 00000038H
        mov     DWORD PTR bits$[rsp], 0
        mov     r8d, 4
        lea     rdx, QWORD PTR f$[rsp]
        lea     rcx, QWORD PTR bits$[rsp]
        call    memcpy
        mov     eax, DWORD PTR bits$[rsp]
        add     rsp, 56                             ; 00000038H
        ret     0
unsigned int float_to_bits1(float) ENDP                            ; float_to_bits1

u$ = 0
f$ = 32
unsigned int float_to_bits2(float) PROC                            ; float_to_bits2
$LN3:
        movss   DWORD PTR [rsp+8], xmm0
        sub     rsp, 24
        movss   xmm0, DWORD PTR f$[rsp]
        movss   DWORD PTR u$[rsp], xmm0
        mov     eax, DWORD PTR u$[rsp]
        add     rsp, 24
        ret     0
```

clang
```asm
float_to_bits1(float):                    # @float_to_bits1(float)
        push    rbp
        mov     rbp, rsp
        movss   dword ptr [rbp - 4], xmm0
        mov     dword ptr [rbp - 8], 0
        mov     eax, dword ptr [rbp - 4]
        mov     dword ptr [rbp - 8], eax
        mov     eax, dword ptr [rbp - 8]
        pop     rbp
        ret
float_to_bits2(float):                    # @float_to_bits2(float)
        push    rbp
        mov     rbp, rsp
        movss   dword ptr [rbp - 4], xmm0
        movss   xmm0, dword ptr [rbp - 4] # xmm0 = mem[0],zero,zero,zero
        movss   dword ptr [rbp - 8], xmm0
        mov     eax, dword ptr [rbp - 8]
        pop     rbp
        ret
```

GCC:
```asm
float_to_bits1(float):
        push    rbp
        mov     rbp, rsp
        movss   DWORD PTR [rbp-20], xmm0
        mov     DWORD PTR [rbp-4], 0
        mov     eax, DWORD PTR [rbp-20]
        mov     DWORD PTR [rbp-4], eax
        mov     eax, DWORD PTR [rbp-4]
        pop     rbp
        ret
float_to_bits2(float):
        push    rbp
        mov     rbp, rsp
        movss   DWORD PTR [rbp-20], xmm0
        movss   xmm0, DWORD PTR [rbp-20]
        movss   DWORD PTR [rbp-4], xmm0
        mov     eax, DWORD PTR [rbp-4]
        pop     rbp
        ret
```

**Comment by StephanTLavavej** [comment]
> Impressive, though, it's disappointing to see that the the compiler has chosen to assume the implementation of certain functions.

That's the wonderful thing about having compilers and libraries whose behavior is specified by International Standards - the compiler can assume the observable behavior of the library and optimize accordingly.

> With MSVC without optimizations it still calls the runtime function which I consider worse than the union solution.

Non-optimized code is inherently slow. This isn't a significant concern, unless the code is so massively slower (e.g. 100x) that it becomes un-debuggable.

The conversion from floating to bits is not a bottleneck for Ryu, even in non-optimized code; the core algorithm takes significantly longer. (Amusingly, Ryu is so inherently fast, its non-optimized performance should be competitive with older algorithms' optimized performance, although I haven't benchmarked this specifically.)

**Comment by marler8997** [comment]
Completely agree with what you said. I'm just stating the difference between the 2 implementations. It seems this one has a slight advantage. Though, I agree with you it's not significant, nor the bottleneck.

I don't see any drawbacks to this implementation, in which case this appears to me to just be a small improvement (with small being the emphasis). Unless there is a drawback I don't see?

**Comment by StephanTLavavej** [comment]
I am far from an expert on strict aliasing (as MSVC doesn't perform such optimizations, and likely never will), but my understanding is that unions do *not* solve this problem.

**Comment by marler8997** [comment]
Did you see Goldbolt's article I sent in my post above?

https://xania.org/200712/cpp-strict-aliasing

He says unions do the trick, but like I said, this is the first I've heard of strict aliasing so Ill have to defer to the experts on that.

**Comment by marler8997** [comment]
I found this article: https://blog.regehr.org/archives/959

A good explanation of the issue.  He mentions that like pointer casting, using unions is also undefined behavior and concludes that the `memcpy` idiom is the best since it is well-defined while remaining "optimizable".

@StephanTLavavej thanks for the guidance.

**Pull request closed without merging**
